# Site settings
title: My Blog, My Journey, My Code
header-img: img/home-bg.png
email: j.grant.brown@gmail.com
copyright_name: jgrantbrown
description: > # this means to ignore newlines until "baseurl:"
  My Coding story!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jgrantbrown
learn_profile: jgrantbrown
email_username: j.grant.brown@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
